const path = require("path");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const fs = require("fs");
const os = require("os");

// Resolve the dev certs generated by office-addin-dev-certs
function getServerOptions() {
  const certDir = path.join(os.homedir(), ".office-addin-dev-certs");
  const cert = path.join(certDir, "localhost.crt");
  const key  = path.join(certDir, "localhost.key");
  if (fs.existsSync(cert) && fs.existsSync(key)) {
    return { type: "https", options: { cert: fs.readFileSync(cert), key: fs.readFileSync(key) } };
  }
  // Fallback: self-signed cert generated by webpack-dev-server itself
  return { type: "https" };
}

module.exports = (env, options) => {
  const isDev = options.mode !== "production";

  return {
    entry: "./src/index.tsx",
    output: {
      path: path.resolve(__dirname, "dist"),
      filename: "taskpane.js",
      clean: true,
    },
    resolve: { extensions: [".ts", ".tsx", ".js"] },
    module: {
      rules: [
        { test: /\.tsx?$/, use: "ts-loader", exclude: /node_modules/ },
        { test: /\.css$/, use: ["style-loader", "css-loader"] },
      ],
    },
    plugins: [
      new HtmlWebpackPlugin({
        template: "./src/index.html",
        filename: "taskpane.html",
      }),
    ],
    devServer: {
      port: 3000,
      server: isDev ? getServerOptions() : undefined,
      headers: { "Access-Control-Allow-Origin": "*" },
      static: { directory: path.resolve(__dirname, "assets"), publicPath: "/assets" },
    },
    devtool: isDev ? "source-map" : false,
  };
};
